"""add_share_token_and_role

Revision ID: 743c6807c5a8
Revises: 05f9fccea011
Create Date: 2026-06-14 20:59:52.777420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743c6807c5a8'
down_revision: Union[str, Sequence[str], None] = '05f9fccea011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_share_token'), 'chat_sessions', ['share_token'], unique=True)
    op.add_column('query_logs', sa.Column('role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'role')
    op.drop_index(op.f('ix_chat_sessions_share_token'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'share_token')
    # ### end Alembic commands ###
